server:
  port: 8888

spring:
  application:
    name: springboot_crud
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmtest?characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  type-aliases-package: com.itheima.springboot.pojo
